<div class="container mx-auto px-8 text-color-ctrl">
	<h2 class="breathing-title underline color-golden-tan text-[32px] xl:text-[48px] text-shadow-[2px_1px_0_black]">
		Privacy (English)</h2>
	<p class="pt-4">
		Introduction:<br>
		We value your privacy and are committed to protecting your personal data. This privacy policy explains
		how
		we collect, use, and protect your personal information when you visit our website. By accessing our
		website,
		you agree to the terms outlined in this policy.<br><br>

		The responsible party for data processing is:<br><br>
		Email: <img src="/footer/mail.png" alt="Email" class="inline mb-2"><br>
		Website: www.lilalunex.dev<br><br>

		Data Collection and Usage:<br>

		We collect personal data when you visit our website, such as IP addresses, browser types, and other
		general
		information through cookies. This data is used to analyze the usage of our website, improve our
		services,
		and enhance user experience.<br><br>

		Google Analytics:<br>

		This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). Google
		Analytics uses cookies to help us analyze how users use the site. The information generated by the
		cookie
		about your use of the website (including your IP address) will be transmitted to and stored by Google on
		servers in the United States.<br>

		We use Google Analytics in compliance with the applicable data protection laws. The data collected is
		anonymized and processed in a way that makes it impossible to identify individual users. If you want to
		prevent Google Analytics from collecting your data, you can disable cookies or use the Google Analytics
		opt-out browser add-on.<br>

		By continuing to use our website, you consent to the processing of data about you by Google Analytics in
		the
		manner and for the purposes set out above.<br><br>

		Hosting:<br>

		Our website is hosted on a VPS provided by Netcup, located in Nürnberg, Germany. The server provider
		processes your data only for the purpose of hosting the website and ensuring its functionality. Netcup
		follows the data protection laws and guarantees a high level of security.<br><br>

		Domain Registration:<br>

		Our domain is registered with Namecheap, a third-party domain registrar. Namecheap processes personal
		data
		to facilitate domain registration and management. For more information on their data protection
		policies,
		please refer to Namecheap's privacy policy.<br><br>

		Links to Third-Party Websites:<br>

		Our website contains links to external websites that are not operated by us. We have no control over the
		content of these sites and assume no responsibility for their privacy practices. Please note that the
		use of these external links is at your own risk. We recommend that you review the privacy policies of
		the respective third-party websites.<br><br>


		Cookies:<br>

		We use cookies to enhance the functionality of our website. Cookies are small text files stored on your
		device. You can control or delete cookies via your browser settings. However, please note that disabling
		cookies may affect the functionality of the website.<br><br>

		User Consent:<br>

		Before we process any personal data via Google Analytics or other tracking services, we will ask for
		your
		explicit consent to process your data. If you do not agree, you can opt-out or disable cookies in your
		browser settings.<br><br>
	</p>

	<h2 class="breathing-title underline color-golden-tan text-[32px] xl:text-[48px] text-shadow-[2px_1px_0_black]">
		Datenschutz (Deutsch)</h2>
	<p class="pt-4">
		Einleitung:<br>
		Wir schätzen Ihre Privatsphäre und setzen uns für den Schutz Ihrer personenbezogenen Daten ein. Diese
		Datenschutzerklärung erklärt, wie wir Ihre personenbezogenen Daten erheben, verwenden und schützen, wenn
		Sie
		unsere Website besuchen. Durch den Zugriff auf unsere Website stimmen Sie den in dieser Erklärung
		beschriebenen Bedingungen zu.<br><br>

		Die verantwortliche Stelle für die Datenverarbeitung ist:<br><br>
		E-Mail: <img src="/footer/mail.png" alt="E-Mail" class="inline mb-2"><br>
		Website: www.lilalunex.dev<br><br>

		Datenerhebung und Nutzung:<br>

		Wir erheben personenbezogene Daten, wenn Sie unsere Website besuchen, wie z. B. IP-Adressen,
		Browser-Typen
		und andere allgemeine Informationen durch Cookies. Diese Daten werden verwendet, um die Nutzung unserer
		Website zu analysieren, unsere Dienstleistungen zu verbessern und die Benutzererfahrung zu
		optimieren.<br><br>

		Google Analytics:<br>

		Diese Website verwendet Google Analytics, einen Webanalysedienst von Google Inc. ("Google"). Google
		Analytics verwendet Cookies, um uns dabei zu unterstützen, zu analysieren, wie Nutzer die Website
		nutzen.
		Die durch den Cookie erzeugten Informationen über Ihre Nutzung der Website (einschließlich Ihrer
		IP-Adresse)
		werden an Google übermittelt und auf Servern in den Vereinigten Staaten gespeichert.<br>

		Wir verwenden Google Analytics in Übereinstimmung mit den geltenden Datenschutzgesetzen. Die erfassten
		Daten
		sind anonymisiert und werden so verarbeitet, dass eine Identifizierung von einzelnen Nutzern
		ausgeschlossen
		ist. Wenn Sie verhindern möchten, dass Google Analytics Ihre Daten erfasst, können Sie Cookies
		deaktivieren
		oder das Google Analytics Opt-out-Browser-Add-on verwenden.<br>

		Durch die fortgesetzte Nutzung unserer Website stimmen Sie der Verarbeitung Ihrer Daten durch Google
		Analytics in der oben beschriebenen Weise und zu den oben genannten Zwecken zu.<br><br>

		Hosting:<br>

		Unsere Website wird auf einem VPS gehostet, der von Netcup bereitgestellt wird, mit Sitz in Nürnberg,
		Deutschland. Der Serveranbieter verarbeitet Ihre Daten ausschließlich zum Zwecke des Hostings der
		Website
		und zur Sicherstellung ihrer Funktionsfähigkeit. Netcup befolgt die Datenschutzgesetze und garantiert
		ein
		hohes Maß an Sicherheit.<br><br>

		Domainregistrierung:<br>

		Unsere Domain ist bei Namecheap, einem externen Domain-Registrar, registriert. Namecheap verarbeitet
		personenbezogene Daten, um die Domainregistrierung und -verwaltung zu ermöglichen. Weitere Informationen
		zu
		den Datenschutzrichtlinien von Namecheap finden Sie in der Datenschutzerklärung von Namecheap.<br><br>

		Links zu Drittwebseiten:<br>

		Unsere Website enthält Links zu externen Webseiten, die nicht von uns betrieben werden. Wir haben keinen
		Einfluss
		auf die Inhalte dieser Seiten und übernehmen keine Verantwortung für deren Datenschutzpraktiken. Bitte
		beachten Sie,
		dass die Nutzung dieser externen Links auf eigene Gefahr erfolgt. Wir empfehlen Ihnen, die
		Datenschutzbestimmungen
		der jeweiligen Drittwebseiten zu lesen.<br><br>

		Cookies:<br>
		Wir verwenden Cookies, um die Funktionalität unserer Website zu verbessern. Cookies sind kleine
		Textdateien,
		die auf Ihrem Gerät gespeichert werden. Sie können Cookies über die Einstellungen Ihres Browsers steuern
		oder löschen. Bitte beachten Sie jedoch, dass das Deaktivieren von Cookies die Funktionalität der
		Website
		beeinträchtigen kann.<br><br>

		Benutzerzustimmung:<br>

		Bevor wir personenbezogene Daten über Google Analytics oder andere Tracking-Dienste verarbeiten, werden
		wir
		um Ihre ausdrückliche Zustimmung zur Verarbeitung Ihrer Daten bitten. Wenn Sie nicht zustimmen, können
		Sie
		die Erfassung ablehnen oder Cookies in den Einstellungen Ihres Browsers deaktivieren.<br><br>
	</p>

</div>